# Generated by Django 5.1.3 on 2024-12-02 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='correo',
            new_name='email',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='Usuarios',
        ),
    ]
