# Generated by Django 5.1.3 on 2024-12-02 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Usuarios', '0002_rename_correo_usuario_email_alter_usuario_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contrasena',
            new_name='password',
        ),
    ]
